#==> 3-8
places = ['Egypt',"Switzerland","London","Paris","Maldives"]
print(places)
print()
print("The sorted list is: ")
print(sorted(places))
print()
print("Orginal List:")
print(places)
print()
print("The reverse sorted list is: ")
print(sorted(places,reverse=True))
print()
print("Orginal List:")
print(places)
print()
places.reverse()
print("The reversed list is: ")
print(places)
print()
places.reverse()
print("After reversing again, the list is: ")
print(places)
print()
places.sort()
print("Sorted list: ")
print(places)
print()
places.sort(reverse=True)
print("Reverse Sorted List is: ")
print(places)

print()
print()

#==> 3-9
guests = ['Ali','Hamza','Bashir']
print(guests[0]+ ", I am inviting you to dinner.")
print(guests[1]+ ", I am inviting you to dinner.")
print(guests[2]+ ", I am inviting you to dinner.")
print()
print("The number of guests I am inviting to dinner is: "+ str(len(guests)))
print()
print()


#==> 3-10
languages = ['Urdu','English','French','German']
languages.pop()
print(languages)
print()
languages.remove(languages[0])
print(languages)
print()
languages.insert(0,'Pashto')
print(languages)
print()
languages.append('Greek')
print(languages)
print()
languages.sort()
print(languages)
print()
languages.reverse
print(languages)
print()